### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by SukkoPera** [StormTrooper/Commodore-Plus4#1]
Hi! I am working on a similar project for the Commodore 16 and I would like to add a PCB as well. Since it uses a lot of the same components as the Plus4, I would like to use your library, am I allowed to do so?

**Comment by StormTrooper** [comment]
Yes, the library is free to use.

**Comment by SukkoPera** [comment]
Great! I'll work on the PCB in the future. In the meantime I have released the schematics, if you are interested: https://github.com/SukkoPera/LittleSixteen.

Thanks!
